package com.unifier.migrationreader;

import org.springframework.stereotype.Component;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.stream.Stream;

/**
 * Reads files generated by migration process that were created with class OperationsRecorder
 */
@Component
public class MigrationFileReader {

    private final String SCHEDULE_MIGRATION_FILE = "/Users/yanoziel/git/cmp/nemo-api-custom-report-builder/ScheduleMigration.txt";
    private final String ON_DEMAND_MIGRATION_FILE = "/Users/yanoziel/git/cmp/nemo-api-custom-report-builder/OnDemandMigration.txt";

    public Stream<String> getScheduleMigrationLines() {
        try {
            return Files.lines(new File(SCHEDULE_MIGRATION_FILE).toPath());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public Stream<String> getOnDemandMigrationLines() {
        try {
            return Files.lines(new File(ON_DEMAND_MIGRATION_FILE).toPath());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

}
